from flask_assets import Environment, Bundle


jquery = Bundle('jquery/jquery.min.js')
popper = Bundle('Popper/popper.min.js')
bootstrap_js = Bundle('bootstrap/js/bootstrap.min.js')
bootstrap_css = Bundle('bootstrap/css/bootstrap.min.css')
main_css = Bundle('scss/main.scss', filters='libsass', depends='scss/*.scss', output='gen/main.css')
chart = Bundle('Chart/Chart.min.js')
openlayers_js = Bundle('OpenLayers/ol-debug.js')
openlayers_css = Bundle('OpenLayers/ol.css')
three = Bundle('three/three.min.js')
three_stl_loader = Bundle('three/STLLoader.js')
mcc_charts = Bundle('js/mcc_charts.js')
mcc_map = Bundle('js/mcc_map.js')
mcc_gl = Bundle('js/mcc_gl.js')
mcc_spectrum = Bundle('js/mcc_spectrum.js')
mcc_status = Bundle('js/mcc_status.js')


assets = Environment()
assets.register('jq_js', jquery)
assets.register('popper_js', popper)
assets.register('bs_js', bootstrap_js)
assets.register('bs_css', bootstrap_css)
assets.register('main_css', main_css)
assets.register('chart_js', chart)
assets.register('openlayers_js', openlayers_js)
assets.register('openlayers_css', openlayers_css)
assets.register('three', three)
assets.register('three_stl_loader', three_stl_loader)
assets.register('mcc_charts', mcc_charts)
assets.register('mcc_map', mcc_map)
assets.register('mcc_gl', mcc_gl)
assets.register('mcc_spectrum', mcc_spectrum)
assets.register('mcc_status', mcc_status)
